export const events = [
    {
        title: "Intro to Neural Networks Workshop",
        date: "2024-09-15",
        time: "18:00 - 20:00",
        location: "AI Lab Downtown",
        link: "https://example.com/neural-networks",
        tags: ["Beginner", "Neural Networks"],
      },
      {
        title: "Machine Learning for Natural Language Processing",
        date: "2024-09-20",
        time: "19:00 - 21:00",
        location: "Tech University, Room 3B",
        link: "https://example.com/ml-nlp",
        tags: ["Intermediate", "NLP"],
      },
      {
        title: "Women in AI Networking Event",
        date: "2024-09-25",
        time: "17:30 - 19:30",
        location: "Innovate Coworking Space",
        link: "https://example.com/women-in-ai",
        tags: ["Networking", "Diversity"],
      },
      {
        title: "Deep Learning with PyTorch",
        date: "2024-10-05",
        time: "10:00 - 16:00",
        location: "Online Webinar",
        link: "https://example.com/pytorch-workshop",
        tags: ["Advanced", "PyTorch"],
      },
      {
        title: "AI Ethics Panel Discussion",
        date: "2024-10-10",
        time: "18:30 - 20:30",
        location: "City Library Auditorium",
        link: "https://example.com/ai-ethics",
        tags: ["Ethics", "Panel"],
      },
      {
        title: "Reinforcement Learning Hackathon",
        date: "2024-10-15",
        time: "09:00 - 18:00",
        location: "Startup Incubator",
        link: "https://example.com/rl-hackathon",
        tags: ["Hackathon", "Reinforcement Learning"],
      },
      {
        title: "AI in Healthcare Symposium",
        date: "2024-10-20",
        time: "13:00 - 17:00",
        location: "Medical Research Center",
        link: "https://example.com/ai-healthcare",
        tags: ["Healthcare", "Symposium"],
      },
      {
        title: "Computer Vision Workshop",
        date: "2024-10-25",
        time: "18:00 - 21:00",
        location: "Tech Hub East",
        link: "https://example.com/computer-vision",
        tags: ["Intermediate", "Computer Vision"],
      },
      {
        title: "AI Startup Pitch Night",
        date: "2024-11-01",
        time: "19:00 - 22:00",
        location: "Venture Capital Office",
        link: "https://example.com/ai-startup-pitch",
        tags: ["Startup", "Networking"],
      },
      {
        title: "Generative AI Art Exhibition",
        date: "2024-11-05",
        time: "11:00 - 20:00",
        location: "Modern Art Gallery",
        link: "https://example.com/generative-ai-art",
        tags: ["Art", "Generative AI"],
      },
      {
        title: "Introduction to TensorFlow",
        date: "2024-11-10",
        time: "14:00 - 17:00",
        location: "Community College, Room 105",
        link: "https://example.com/intro-tensorflow",
        tags: ["Beginner", "TensorFlow"],
      },
      {
        title: "AI in Finance: Trend Prediction",
        date: "2024-11-15",
        time: "09:00 - 12:00",
        location: "Financial District Conference Center",
        link: "https://example.com/ai-finance",
        tags: ["Finance", "Prediction"],
      },
      {
        title: "Natural Language Processing Masterclass",
        date: "2024-11-20",
        time: "10:00 - 16:00",
        location: "Language Institute",
        link: "https://example.com/nlp-masterclass",
        tags: ["Advanced", "NLP"],
      },
      {
        title: "AI for Game Development Workshop",
        date: "2024-11-25",
        time: "13:00 - 18:00",
        location: "Game Dev Studio",
        link: "https://example.com/ai-gamedev",
        tags: ["Game Development", "AI"],
      },
      {
        title: "Machine Learning Ops (MLOps) Conference",
        date: "2024-12-01",
        time: "09:00 - 17:00",
        location: "Convention Center",
        link: "https://example.com/mlops-conf",
        tags: ["MLOps", "Conference"],
      },
      {
        title: "AI in Robotics Demonstration",
        date: "2024-12-05",
        time: "15:00 - 18:00",
        location: "Robotics Research Lab",
        link: "https://example.com/ai-robotics",
        tags: ["Robotics", "Demonstration"],
      },
      {
        title: "Data Science for Beginners Workshop",
        date: "2024-12-10",
        time: "18:00 - 20:00",
        location: "Public Library, Computer Lab",
        link: "https://example.com/data-science-beginners",
        tags: ["Beginner", "Data Science"],
      },
      {
        title: "AI in Climate Change Research Seminar",
        date: "2024-12-15",
        time: "14:00 - 16:00",
        location: "Environmental Studies Building",
        link: "https://example.com/ai-climate-change",
        tags: ["Climate", "Research"],
      },
      {
        title: "Explainable AI Workshop",
        date: "2024-12-20",
        time: "10:00 - 13:00",
        location: "Tech Incubator",
        link: "https://example.com/explainable-ai",
        tags: ["XAI", "Workshop"],
      },
      {
        title: "AI and IoT Integration Symposium",
        date: "2024-12-25",
        time: "09:00 - 18:00",
        location: "Smart City Exhibition Hall",
        link: "https://example.com/ai-iot-symposium",
        tags: ["IoT", "Integration"],
      },
    ];