export const events = [
  {
    title: "Intro to Neural Networks Workshop",
    date: "2024-09-17",
    time: "18:00 - 20:00",
    location: "AI Lab Downtown",
    link: "https://pyimagesearch.com/2021/05/06/introduction-to-neural-networks/",
    tags: ["Beginner", "Neural Networks"],
  },
  {
    title: "Machine Learning for Natural Language Processing",
    date: "2024-09-24",
    time: "19:00 - 21:00",
    location: "Tech University, Room 3B",
    link: "https://www.nlpsummit.org/nlp-summit-2024/",
    tags: ["Intermediate", "NLP"],
  },
  {
    title: "Women in AI Networking Event",
    date: "2024-10-01",
    time: "17:30 - 19:30",
    location: "Innovate Coworking Space",
    link: "https://www.womeninai.co/global-network",
    tags: ["Networking", "Diversity"],
  },
  {
    title: "Deep Learning with PyTorch",
    date: "2024-10-08",
    time: "10:00 - 16:00",
    location: "Online Webinar",
    link: "https://pytorch.org/tutorials/",
    tags: ["Advanced", "PyTorch"],
  },
  {
    title: "AI Ethics Panel Discussion",
    date: "2024-10-15",
    time: "18:30 - 20:30",
    location: "City Library Auditorium",
    link: "https://www.unesco.org/en/artificial-intelligence/recommendation-ethics",
    tags: ["Ethics", "Panel"],
  },
  {
    title: "Reinforcement Learning Hackathon",
    date: "2024-10-22",
    time: "09:00 - 18:00",
    location: "Startup Incubator",
    link: "https://spinningup.openai.com/en/latest/",
    tags: ["Hackathon", "Reinforcement Learning"],
  },
  {
    title: "AI in Healthcare Symposium",
    date: "2024-10-29",
    time: "13:00 - 17:00",
    location: "Medical Research Center",
    link: "https://www.who.int/health-topics/artificial-intelligence",
    tags: ["Healthcare", "Symposium"],
  },
  {
    title: "Computer Vision Workshop",
    date: "2024-11-05",
    time: "18:00 - 21:00",
    location: "Tech Hub East",
    link: "https://www.opencv.org/courses/",
    tags: ["Intermediate", "Computer Vision"],
  },
  {
    title: "AI Startup Pitch Night",
    date: "2024-11-12",
    time: "19:00 - 22:00",
    location: "Venture Capital Office",
    link: "https://www.ycombinator.com/library/6g-ai-startup-landscape",
    tags: ["Startup", "Networking"],
  },
  {
    title: "Generative AI Art Exhibition",
    date: "2024-11-19",
    time: "11:00 - 20:00",
    location: "Modern Art Gallery",
    link: "https://aiartists.org/ai-generated-art-tools",
    tags: ["Art", "Generative AI"],
  },
  {
    title: "Introduction to TensorFlow",
    date: "2024-11-26",
    time: "14:00 - 17:00",
    location: "Community College, Room 105",
    link: "https://www.tensorflow.org/learn",
    tags: ["Beginner", "TensorFlow"],
  },
  {
    title: "AI in Finance: Trend Prediction",
    date: "2024-12-03",
    time: "09:00 - 12:00",
    location: "Financial District Conference Center",
    link: "https://www.investopedia.com/terms/a/artificial-intelligence-ai",
    tags: ["Finance", "Prediction"],
  },
  {
    title: "Natural Language Processing Masterclass",
    date: "2024-12-10",
    time: "10:00 - 16:00",
    location: "Language Institute",
    link: "https://web.stanford.edu/class/cs224n/",
    tags: ["Advanced", "NLP"],
  },
  {
    title: "AI for Game Development Workshop",
    date: "2024-12-17",
    time: "13:00 - 18:00",
    location: "Game Dev Studio",
    link: "https://unity.com/products/machine-learning-agents",
    tags: ["Game Development", "AI"],
  },
  {
    title: "Machine Learning Ops (MLOps) Conference",
    date: "2024-12-24",
    time: "09:00 - 17:00",
    location: "Convention Center",
    link: "https://ml-ops.org/",
    tags: ["MLOps", "Conference"],
  },
  {
    title: "AI in Robotics Demonstration",
    date: "2024-12-31",
    time: "15:00 - 18:00",
    location: "Robotics Research Lab",
    link: "https://www.edx.org/course/artificial-intelligence-for-robotics",
    tags: ["Robotics", "Demonstration"],
  },
  {
    title: "Data Science for Beginners Workshop",
    date: "2025-01-07",
    time: "18:00 - 20:00",
    location: "Public Library, Computer Lab",
    link: "https://www.datacamp.com/courses/introduction-to-data-science-in-python",
    tags: ["Beginner", "Data Science"],
  },
  {
    title: "AI in Climate Change Research Seminar",
    date: "2025-01-14",
    time: "14:00 - 16:00",
    location: "Environmental Studies Building",
    link: "https://www.climatechange.ai/",
    tags: ["Climate", "Research"],
  },
  {
    title: "Explainable AI Workshop",
    date: "2025-01-21",
    time: "10:00 - 13:00",
    location: "Tech Incubator",
    link: "https://christophm.github.io/interpretable-ml-book/",
    tags: ["XAI", "Workshop"],
  },
  {
    title: "AI and IoT Integration Symposium",
    date: "2025-01-28",
    time: "09:00 - 18:00",
    location: "Smart City Exhibition Hall",
    link: "https://www.iotforall.com/iot-and-ai",
    tags: ["IoT", "Integration"],
  },
];